//These are the same as the GLFW ones with slightly different naming

#pragma once

#define PYRO_KEY_SPACE              32
#define PYRO_KEY_APOSTROPHE         39
#define PYRO_KEY_COMMA              44
#define PYRO_KEY_MINUS              45
#define PYRO_KEY_FULL_STOP          46
#define PYRO_KEY_SLASH_FORWARD      47
#define PYRO_KEY_0                  48
#define PYRO_KEY_1                  49
#define PYRO_KEY_2                  50
#define PYRO_KEY_3                  51
#define PYRO_KEY_4                  52
#define PYRO_KEY_5                  53
#define PYRO_KEY_6                  54
#define PYRO_KEY_7                  55
#define PYRO_KEY_8                  56
#define PYRO_KEY_9                  57
#define PYRO_KEY_SEMICOLON          59
#define PYRO_KEY_EQUALS             61
#define PYRO_KEY_A                  65
#define PYRO_KEY_B                  66
#define PYRO_KEY_C                  67
#define PYRO_KEY_D                  68
#define PYRO_KEY_E                  69
#define PYRO_KEY_F                  70
#define PYRO_KEY_G                  71
#define PYRO_KEY_H                  72
#define PYRO_KEY_I                  73
#define PYRO_KEY_J                  74
#define PYRO_KEY_K                  75
#define PYRO_KEY_L                  76
#define PYRO_KEY_M                  77
#define PYRO_KEY_N                  78
#define PYRO_KEY_O                  79
#define PYRO_KEY_P                  80
#define PYRO_KEY_Q                  81
#define PYRO_KEY_R                  82
#define PYRO_KEY_S                  83
#define PYRO_KEY_T                  84
#define PYRO_KEY_U                  85
#define PYRO_KEY_V                  86
#define PYRO_KEY_W                  87
#define PYRO_KEY_X                  88
#define PYRO_KEY_Y                  89
#define PYRO_KEY_Z                  90
#define PYRO_KEY_BRACKET_LEFT       91
#define PYRO_KEY_SLASH_BACKWARD     92
#define PYRO_KEY_BRACKET_RIGHT      93
#define PYRO_KEY_GRAVE_ACCENT       96
#define PYRO_KEY_WORLD_1            161 /* non-US #1 */
#define PYRO_KEY_WORLD_2            162 /* non-US #2 */
#define PYRO_KEY_ESCAPE             256
#define PYRO_KEY_ENTER              257
#define PYRO_KEY_TAB                258
#define PYRO_KEY_BACKSPACE          259
#define PYRO_KEY_INSERT             260
#define PYRO_KEY_DELETE             261
#define PYRO_KEY_ARROW_RIGHT        262
#define PYRO_KEY_ARROW_LEFT         263
#define PYRO_KEY_ARROW_DOWN         264
#define PYRO_KEY_ARROW_UP           265
#define PYRO_KEY_PAGE_UP            266
#define PYRO_KEY_PAGE_DOWN          267
#define PYRO_KEY_HOME               268
#define PYRO_KEY_END                269
#define PYRO_KEY_CAPS_LOCK          280
#define PYRO_KEY_SCROLL_LOCK        281
#define PYRO_KEY_NUM_LOCK           282
#define PYRO_KEY_PRINT_SCREEN       283
#define PYRO_KEY_PAUSE              284
#define PYRO_KEY_F1                 290
#define PYRO_KEY_F2                 291
#define PYRO_KEY_F3                 292
#define PYRO_KEY_F4                 293
#define PYRO_KEY_F5                 294
#define PYRO_KEY_F6                 295
#define PYRO_KEY_F7                 296
#define PYRO_KEY_F8                 297
#define PYRO_KEY_F9                 298
#define PYRO_KEY_F10                299
#define PYRO_KEY_F11                300
#define PYRO_KEY_F12                301
#define PYRO_KEY_F13                302
#define PYRO_KEY_F14                303
#define PYRO_KEY_F15                304
#define PYRO_KEY_F16                305
#define PYRO_KEY_F17                306
#define PYRO_KEY_F18                307
#define PYRO_KEY_F19                308
#define PYRO_KEY_F20                309
#define PYRO_KEY_F21                310
#define PYRO_KEY_F22                311
#define PYRO_KEY_F23                312
#define PYRO_KEY_F24                313
#define PYRO_KEY_F25                314
#define PYRO_KEY_KEYPAD_0           320
#define PYRO_KEY_KEYPAD_1           321
#define PYRO_KEY_KEYPAD_2           322
#define PYRO_KEY_KEYPAD_3           323
#define PYRO_KEY_KEYPAD_4           324
#define PYRO_KEY_KEYPAD_5           325
#define PYRO_KEY_KEYPAD_6           326
#define PYRO_KEY_KEYPAD_7           327
#define PYRO_KEY_KEYPAD_8           328
#define PYRO_KEY_KEYPAD_9           329
#define PYRO_KEY_KEYPAD_DECIMAL     330
#define PYRO_KEY_KEYPAD_DIVIDE      331
#define PYRO_KEY_KEYPAD_MULTIPLY    332
#define PYRO_KEY_KEYPAD_SUBTRACT    333
#define PYRO_KEY_KEYPAD_ADD         334
#define PYRO_KEY_KEYPAD_ENTER       335
#define PYRO_KEY_KEYPAD_EQUALS      336
#define PYRO_KEY_SHIFT_LEFT         340
#define PYRO_KEY_CONTROL_LEFT       341
#define PYRO_KEY_ALT_LEFT           342
#define PYRO_KEY_SUPER_LEFT         343
#define PYRO_KEY_SHIFT_RIGHT        344
#define PYRO_KEY_CONTROL_RIGHT      345
#define PYRO_KEY_ALT_RIGHT          346
#define PYRO_KEY_SUPER_RIGHT        347
#define PYRO_KEY_MENU               348